/**
 * Snippet Generator - Auto-generazione snippet da schema placeholder
 *
 * Genera automaticamente snippet comuni da DM329_PLACEHOLDERS:
 * - Loop base per ogni array
 * - Tabelle HTML per array con campi
 * - Condizioni "se presente" per array
 */

import type { PlaceholderDefinition } from '../types/template';
import { generateLoopCode, generateTableCode, generateConditionalCode } from './codeGenerators';

export interface TemplateSnippet {
  id: string;
  name: string;
  category: 'testi' | 'tabelle' | 'condizionali' | 'calcoli' | 'loop';
  description: string;
  code: string;
  preview?: string;
  requiredData: string[];
  autoGenerated?: boolean;
}

/**
 * Estrae tutti i placeholder array dallo schema
 */
function extractArrayPlaceholders(schema: PlaceholderDefinition[]): PlaceholderDefinition[] {
  const arrays: PlaceholderDefinition[] = [];

  const findArrays = (items: PlaceholderDefinition[]) => {
    items.forEach(item => {
      if (item.type.includes('array')) {
        arrays.push(item);
      }
      if (item.children) {
        findArrays(item.children);
      }
    });
  };

  findArrays(schema);
  return arrays;
}

/**
 * Estrae i campi figli di un placeholder array
 */
function getArrayFields(placeholder: PlaceholderDefinition): string[] {
  if (!placeholder.children || placeholder.children.length === 0) {
    return [];
  }

  return placeholder.children.map(child => {
    // Rimuovi prefisso array (es. "serbatoi[].codice" -> "codice")
    const parts = child.path.split('[].');
    return parts.length > 1 ? parts[1] : child.path.split('.').pop() || child.path;
  });
}

/**
 * Genera nome human-readable da path
 */
function humanizePath(path: string): string {
  // "serbatoi" -> "Serbatoi"
  const cleanPath = path.replace('[]', '').split('.').pop() || path;
  return cleanPath.charAt(0).toUpperCase() + cleanPath.slice(1);
}

/**
 * Genera snippet loop base per un array
 */
export function generateLoopSnippet(placeholder: PlaceholderDefinition): TemplateSnippet {
  const arrayPath = placeholder.path.replace('[]', '');
  const fields = getArrayFields(placeholder);
  const name = humanizePath(arrayPath);

  // Prendi primi 3 campi per loop semplice
  const selectedFields = fields.slice(0, 3);

  const code = generateLoopCode({
    arrayPath,
    outputType: 'list',
    selectedFields,
    customTemplate: selectedFields.map(f => `{{this.${f}}}`).join(' - ')
  });

  return {
    id: `loop_${arrayPath}`,
    name: `Loop ${name}`,
    category: 'loop',
    description: `Ciclo su tutti i ${name.toLowerCase()} con campi principali`,
    code,
    requiredData: [arrayPath],
    autoGenerated: true
  };
}

/**
 * Genera snippet tabella HTML per un array
 */
export function generateTableSnippet(placeholder: PlaceholderDefinition): TemplateSnippet {
  const arrayPath = placeholder.path.replace('[]', '');
  const fields = getArrayFields(placeholder);
  const name = humanizePath(arrayPath);

  // Usa tutti i campi disponibili per la tabella
  const code = generateTableCode(arrayPath, fields);

  return {
    id: `table_${arrayPath}`,
    name: `Tabella ${name}`,
    category: 'tabelle',
    description: `Tabella completa con tutti i campi ${name.toLowerCase()}`,
    code,
    requiredData: [arrayPath],
    autoGenerated: true
  };
}

/**
 * Genera snippet condizione "se presente" per un array
 */
export function generateArrayExistsSnippet(placeholder: PlaceholderDefinition): TemplateSnippet {
  const arrayPath = placeholder.path.replace('[]', '');
  const name = humanizePath(arrayPath);

  const code = generateConditionalCode({
    field: `${arrayPath}.length`,
    operator: 'gt',
    value: 0,
    trueContent: `Sono presenti {{${arrayPath}.length}} ${name.toLowerCase()}.`,
    falseContent: `Non sono presenti ${name.toLowerCase()}.`
  });

  return {
    id: `exists_${arrayPath}`,
    name: `Se presente ${name}`,
    category: 'condizionali',
    description: `Mostra testo solo se ci sono ${name.toLowerCase()}`,
    code,
    requiredData: [arrayPath],
    autoGenerated: true
  };
}

/**
 * Genera tutti gli snippet automatici da uno schema
 */
export function generateAllSnippets(schema: PlaceholderDefinition[]): TemplateSnippet[] {
  const snippets: TemplateSnippet[] = [];
  const arrayPlaceholders = extractArrayPlaceholders(schema);

  arrayPlaceholders.forEach(placeholder => {
    // Skip array senza children (non generabili)
    if (!placeholder.children || placeholder.children.length === 0) {
      return;
    }

    // Loop base
    snippets.push(generateLoopSnippet(placeholder));

    // Tabella HTML
    snippets.push(generateTableSnippet(placeholder));

    // Condizione "se presente"
    snippets.push(generateArrayExistsSnippet(placeholder));
  });

  return snippets;
}

/**
 * Filtra snippet per categoria
 */
export function filterSnippetsByCategory(
  snippets: TemplateSnippet[],
  category: TemplateSnippet['category']
): TemplateSnippet[] {
  return snippets.filter(s => s.category === category);
}

/**
 * Cerca snippet per query testuale
 */
export function searchSnippets(snippets: TemplateSnippet[], query: string): TemplateSnippet[] {
  if (!query) return snippets;

  const lowerQuery = query.toLowerCase();
  return snippets.filter(snippet =>
    snippet.name.toLowerCase().includes(lowerQuery) ||
    snippet.description.toLowerCase().includes(lowerQuery) ||
    snippet.code.toLowerCase().includes(lowerQuery)
  );
}
