/**
 * Template Snippets - Libreria snippet manuali + auto-generati
 *
 * Snippet predefiniti per casi d'uso comuni DM329
 */

import type { TemplateSnippet } from './snippetGenerator';
import { generateAllSnippets } from './snippetGenerator';
import { DM329_PLACEHOLDERS } from './templateDataSchema';

/**
 * Snippet manuali per casi speciali
 */
export const MANUAL_SNIPPETS: TemplateSnippet[] = [
  // ===== TESTI STANDARD =====
  {
    id: 'intestazione_cliente',
    name: 'Intestazione Cliente Completa',
    category: 'testi',
    description: 'Nome e indirizzo completo del cliente',
    code: `{{cliente.ragione_sociale}}\n{{formatIndirizzo cliente.sede_legale}}`,
    requiredData: ['cliente'],
    autoGenerated: false
  },

  {
    id: 'intestazione_impianto',
    name: 'Intestazione Impianto',
    category: 'testi',
    description: 'Indirizzo completo del sito impianto',
    code: `Sito impianto: {{formatIndirizzo sito_impianto}}`,
    requiredData: ['sito_impianto'],
    autoGenerated: false
  },

  {
    id: 'dichiarazione_tecnico',
    name: 'Dichiarazione Tecnico con Data',
    category: 'testi',
    description: 'Firma del tecnico con data formattata',
    code: `Il sottoscritto {{tecnico.nome}} {{tecnico.cognome}}, in qualità di {{tecnico.qualifica}}, dichiara quanto segue.\n\nData: {{formatDate relazione.data_relazione "DD/MM/YYYY"}}\n\nFirma: _________________________`,
    requiredData: ['tecnico', 'relazione'],
    autoGenerated: false
  },

  {
    id: 'dati_pratica',
    name: 'Dati Pratica Completi',
    category: 'testi',
    description: 'Numero pratica, tipo verifica e data',
    code: `Pratica N. {{pratica.numero}}\nTipo Verifica: {{pratica.tipo_verifica}}\nData: {{formatDate pratica.data_verifica "DD/MM/YYYY"}}`,
    requiredData: ['pratica'],
    autoGenerated: false
  },

  // ===== CONDIZIONALI =====
  {
    id: 'locale_dedicato',
    name: 'Locale Dedicato',
    category: 'condizionali',
    description: 'Verifica se impianto ha locale dedicato',
    code: `{{#if impianto.locale_dedicato}}\nL'impianto è installato in locale dedicato conforme alla normativa vigente.\n{{else}}\nL'impianto è installato in locale non dedicato.\n{{/if}}`,
    requiredData: ['impianto'],
    autoGenerated: false
  },

  {
    id: 'verifica_spessimetrica',
    name: 'Esito Verifica Spessimetrica',
    category: 'condizionali',
    description: 'Mostra esito verifica con dettagli se eseguita',
    code: `{{#if verifica.spessimetrica_eseguita}}\nVerifica spessimetrica eseguita: {{verifica.spessimetrica_esito}}\n{{#if (eq verifica.spessimetrica_esito 'POSITIVO')}}\n✓ Spessori residui conformi ai valori ammissibili.\n{{else}}\n⚠️ Rilevate criticità da valutare.\n{{/if}}\n{{else}}\nVerifica spessimetrica non eseguita.\n{{/if}}`,
    requiredData: ['verifica'],
    autoGenerated: false
  },

  // ===== CALCOLI =====
  {
    id: 'calcolo_psv_verifica',
    name: 'Calcolo PS×V con Verifica DM329',
    category: 'calcoli',
    description: 'Calcola PS×V per ogni serbatoio e verifica soglia DM329',
    code: `{{#each serbatoi}}\nSerbatoio {{this.codice}}:\n- PS: {{this.ps_pressione_max}} bar\n- Volume: {{this.volume}} L\n- PS×V: {{psXvolume this.ps_pressione_max this.volume}} bar·L\n\n{{#if (gt (psXvolume this.ps_pressione_max this.volume) 8000)}}\n⚠️ SOGGETTO A VERIFICA PERIODICA (PS×V > 8000)\nCategoria PED: {{this.categoria_ped}}\n{{else}}\n✓ Non soggetto a verifica periodica INAIL\n{{/if}}\n\n{{/each}}`,
    requiredData: ['serbatoi'],
    autoGenerated: false
  },

  {
    id: 'tipo_verifica_dm329',
    name: 'Tipo Verifica DM329 Automatico',
    category: 'calcoli',
    description: 'Determina automaticamente tipo verifica in base a PS×V',
    code: `{{#each serbatoi}}\n{{#if (gte this.ps_x_volume 13000)}}\nTipo verifica: DECENNALE (PS×V ≥ 13000)\n{{else}}\n{{#if (gte this.ps_x_volume 8000)}}\nTipo verifica: QUINQUENNALE (PS×V ≥ 8000)\n{{else}}\nTipo verifica: Non soggetto (PS×V < 8000)\n{{/if}}\n{{/if}}\n{{/each}}`,
    requiredData: ['serbatoi'],
    autoGenerated: false
  },

  // ===== TABELLE SPECIALI =====
  {
    id: 'tabella_riepilogo_impianto',
    name: 'Tabella Riepilogo Impianto',
    category: 'tabelle',
    description: 'Tabella con conteggi apparecchiature',
    code: `<table>\n  <thead>\n    <tr>\n      <th>Tipo Apparecchiatura</th>\n      <th>Quantità</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td>Serbatoi</td>\n      <td>{{serbatoi.length}}</td>\n    </tr>\n    <tr>\n      <td>Compressori</td>\n      <td>{{compressori.length}}</td>\n    </tr>\n    <tr>\n      <td>Essiccatori</td>\n      <td>{{essiccatori.length}}</td>\n    </tr>\n    <tr>\n      <td>Filtri</td>\n      <td>{{filtri.length}}</td>\n    </tr>\n    <tr>\n      <td><strong>Totale</strong></td>\n      <td><strong>{{add (add (add serbatoi.length compressori.length) essiccatori.length) filtri.length}}</strong></td>\n    </tr>\n  </tbody>\n</table>`,
    requiredData: ['serbatoi', 'compressori', 'essiccatori', 'filtri'],
    autoGenerated: false
  }
];

/**
 * Snippet auto-generati da schema
 */
export const AUTO_GENERATED_SNIPPETS = generateAllSnippets(DM329_PLACEHOLDERS);

/**
 * Tutti gli snippet disponibili (manuali + auto-generati)
 */
export const ALL_SNIPPETS: TemplateSnippet[] = [
  ...MANUAL_SNIPPETS,
  ...AUTO_GENERATED_SNIPPETS
];

/**
 * Snippet raggruppati per categoria
 */
export const SNIPPETS_BY_CATEGORY = {
  testi: ALL_SNIPPETS.filter(s => s.category === 'testi'),
  tabelle: ALL_SNIPPETS.filter(s => s.category === 'tabelle'),
  condizionali: ALL_SNIPPETS.filter(s => s.category === 'condizionali'),
  calcoli: ALL_SNIPPETS.filter(s => s.category === 'calcoli'),
  loop: ALL_SNIPPETS.filter(s => s.category === 'loop')
};

/**
 * Cerca snippet per nome o descrizione
 */
export function findSnippet(id: string): TemplateSnippet | undefined {
  return ALL_SNIPPETS.find(s => s.id === id);
}
